source 'https://rubygems.org'

ruby '2.3.0'

# Must be loaded before "elasticsearch-model"
gem 'kaminari'
gem 'kaminari-bootstrap'

gem 'ancestry'
gem 'asset_sync'
gem 'autoprefixer-rails'
gem 'aws-sdk-v1'
gem 'bcrypt'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap-sass'
gem 'bootstrap-select-rails'
gem 'coffee-rails'
gem 'devise'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'font-awesome-sass'
gem 'geocoder'
gem 'ice_cube'
gem 'intercom'
gem 'jbuilder'
gem 'jquery-fileupload-rails'
gem 'jquery-minicolors-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'json-jwt'
gem 'koala'
gem 'mini_magick'
gem 'minimalizer'
gem 'normalize-rails'
gem 'paperclip'
gem 'pg'
gem 'platform-api'
gem 'puma'
gem 'quiet_assets'
gem 'rack-timeout'
gem 'rails'
gem 'react-rails'
gem 'recurring_select'
gem 'sanitize'
gem 'sass-rails'
gem 'sidekiq'
gem 'slim-rails'
gem 'summernote-rails'
gem 'turbolinks'
gem 'twitter-typeahead-rails'
gem 'uglifier'

group :development, :test do
  gem 'dotenv-rails'
  gem 'erd'
  gem 'spring'
end

group :production do
  gem 'bonsai-elasticsearch-rails'
  gem 'dalli'
  gem 'newrelic_rpm'
  gem 'rails_12factor'
end
