development:
  adapter: postgresql
  database: impact_development
  encoding: unicode
test:
  adapter: postgresql
  database: impact_test
  encoding: unicode
production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
