development:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>
  aws_s3_region: <%= ENV['AWS_S3_REGION'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  host: impact.test
  listing_host: listings.impact.test
  secret_key_base: 19cdca1a5fa5b91b14515139d534068814b4a914652c5ade6eca3274d33fafae35ab67e583b546651b87075dbed0136468c85fc8dfbdc10fb65967f9663f9efb
  support_email: support@impact.test
  lambda_api_endpoint: <%= ENV['LAMBDA_API_ENDPOINT'] %>
  lambda_api_key: <%= ENV['LAMBDA_API_KEY'] %>

test:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>
  aws_s3_region: <%= ENV['AWS_S3_REGION'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  host: impact.test
  listing_host: listings.impact.test
  secret_key_base: 27237dddce13b93677b648eb64a303cbdedd7a0e7b8e4a795971a2eb27325710d3f4b75b416f4c56a1a0f3b82612d5c15d4cefee490d270691dd9ac453804b17
  support_email: support@impact.test
  lambda_api_endpoint: <%= ENV['LAMBDA_API_ENDPOINT'] %>
  lambda_api_key: <%= ENV['LAMBDA_API_KEY'] %>

production:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_cloudfront_host: <%= ENV['AWS_CLOUDFRONT_HOST'] %>
  aws_s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>
  aws_s3_region: <%= ENV['AWS_S3_REGION'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ses_smtp_address: <%= ENV['AWS_SES_SMTP_ADDRESS'] %>
  aws_ses_smtp_password: <%= ENV['AWS_SES_SMTP_PASSWORD'] %>
  aws_ses_smtp_port: <%= ENV['AWS_SES_SMTP_PORT'] %>
  aws_ses_smtp_username: <%= ENV['AWS_SES_SMTP_USERNAME'] %>
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  host: <%= ENV['HOST'] %>
  listing_host: <%= ENV['LISTING_HOST'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  support_email: <%= ENV['SUPPORT_EMAIL'] %>
  invite_email: <%= ENV['INVITE_EMAIL'] %>
  buzz_email: <%= ENV['BUZZ_EMAIL'] %>
  lambda_api_endpoint: <%= ENV['LAMBDA_API_ENDPOINT'] %>
  lambda_api_key: <%= ENV['LAMBDA_API_KEY'] %>
